name: Config Update
on:
  repository_dispatch:
    types: [runtime-config-update]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Write content
        env:
          FILE_PATH: Config/ConfigFile.json
          CONTENT_B64: ${{ github.event.client_payload.content_base64 }}
          COMMIT_MSG: ${{ github.event.client_payload.message }}
        run: |
          echo "$CONTENT_B64" | base64 -d > "$FILE_PATH"
          git config user.name "Runtime Bot"
          git config user.email "bot@example.com"
          git add "$FILE_PATH"
          git commit -m "${COMMIT_MSG:-Update from runtime}" || echo "No changes"
          git push
